  
name: Publish Site

on:
  push:
    branches:
    - master

jobs:
  publish_site:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy
      env:
        JAVA_OPTS: -Xms512m -Xmx1024m
        BUNDLE_GEMFILE: content/Gemfile
        JEKYLL_ENV: production
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
      run: |
        set -ex
        sudo pip install awscli
        aws --version
        sudo apt-get update
        sudo apt-get install ruby-dev
        sudo gem install bundler --force
        sudo gem update --system
        gem --version
        echo "$( gem list | grep bundler )"
        bundle install --gemfile $BUNDLE_GEMFILE --path vendor/bundle
        bundle exec jekyll build -s content -d content/_site
        echo "Publish in S3..."
        aws s3 sync content/_site s3://$S3_BUCKET > aws_sync_jekyll.log
        aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_ID --paths "/*" > aws_sync_jekyll.log
